#8080:测试  #8082:测试
server:
  port: 8080
  #访问时需要加上此参
  servlet:
    context-path: #/twh

#springboot的配置
spring:
  application:
    name: twh  #appName

#事务回滚控制
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource: #定义数据源
    #下面这两个配置，可以在每次连接的时候判断一些连接是否有效
    druid.test-on-borrow: true
    druid.test-while-idle: true
    db-type: MYSQL
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/twh?useSSL=false&autoReconnect=true&serverTimezone=GMT%2B8&characterEncoding=utf8&rewriteBatchedStatements=true
    username: root
    password: 123456

  resources:
    static-locations: classpath:/templates  #访问静态页面

  mvc:
    view:
      prefix: /templates/
      suffix: .html

  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 127.0.0.1 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password:   # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 20 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    connect-timeout: 1000 # 连接超时时间（毫秒）

mybatis:  #mybatyis的配置
  mapper-locations: classpath:mapper/*Mapper.xml #指定mapper的配置文件的路径是mapper文件夹下的所有 xml文件。
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml  # 指定Mapper XML文件的位置，可以使用通配符
  type-aliases-package: com.twh.door.entity.POJO   # 指定实体类的包路径，用于别名注册
  configuration:
    map-underscore-to-camel-case: true       # 开启驼峰命名自动映射
    cache-enabled: true                      # 开启全局二级缓存
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # MyBatis 日志输出到控制台


  #日志级别
logging:
  level:
    root: warn
    #trace时 四个级别都打印出来，info时打印info和warn,warn时只打印warn,debug时打印debug,warn,info
    com.twh.door*: debug
  #日志输出文件
    #file:
    #name: log/log_202405/lab-0523.log

timer:
  TimerProgram:
    timerStr: 12345678901qaz2wsx3edc8uhb9ijn0okm-['=]


